Update MultKAN.py
Fix: call to save_act_in_fit() without required positional argument

Fix is for bug:
TypeError: MultKAN.recover_save_act_in_fit() missing 1 required positional argument: 'old_save_act'
... kan/MultKan.py:940